; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mllvm -riscv-enable-insert-nop < %s \
; RUN:   | FileCheck -check-prefix=CHECK %s

; Test basic NOP insertion: every 8 instructions should have a NOP inserted
define i32 @test_basic_nop_insertion(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: test_basic_nop_insertion:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, 1
; CHECK-NEXT:    addi a1, a1, 1
; CHECK-NEXT:    addi a2, a2, 1
; CHECK-NEXT:    addi a3, a3, 1
; CHECK-NEXT:    addi a0, a0, 2
; CHECK-NEXT:    addi a1, a1, 2
; CHECK-NEXT:    addi a2, a2, 2
; CHECK-NEXT:    addi a3, a3, 2
; CHECK-NEXT:    addi x0, x0, 0
; CHECK-NEXT:    addi a0, a0, 3
; CHECK-NEXT:    addi a1, a1, 3
; CHECK-NEXT:    addi a2, a2, 3
; CHECK-NEXT:    addi a3, a3, 3
; CHECK-NEXT:    addi a0, a0, 4
; CHECK-NEXT:    addi a1, a1, 4
; CHECK-NEXT:    addi a2, a2, 4
; CHECK-NEXT:    addi a3, a3, 4
; CHECK-NEXT:    addi x0, x0, 0
; CHECK-NEXT:    ret
  %1 = add i32 %a, 1
  %2 = add i32 %b, 1
  %3 = add i32 %c, 1
  %4 = add i32 %d, 1
  %5 = add i32 %1, 2
  %6 = add i32 %2, 2
  %7 = add i32 %3, 2
  %8 = add i32 %4, 2
  %9 = add i32 %5, 3
  %10 = add i32 %6, 3
  %11 = add i32 %7, 3
  %12 = add i32 %8, 3
  %13 = add i32 %9, 4
  %14 = add i32 %10, 4
  %15 = add i32 %11, 4
  %16 = add i32 %12, 4
  ret i32 %16
}

; Test that NOP is not inserted after terminator (ret) instruction
define i32 @test_no_nop_after_terminator(i32 %a) {
; CHECK-LABEL: test_no_nop_after_terminator:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, 1
; CHECK-NEXT:    addi a0, a0, 2
; CHECK-NEXT:    addi a0, a0, 3
; CHECK-NEXT:    addi a0, a0, 4
; CHECK-NEXT:    addi a0, a0, 5
; CHECK-NEXT:    addi a0, a0, 6
; CHECK-NEXT:    addi a0, a0, 7
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    addi x0, x0, 0
; CHECK-NEXT:    ret
  %1 = add i32 %a, 1
  %2 = add i32 %1, 2
  %3 = add i32 %2, 3
  %4 = add i32 %3, 4
  %5 = add i32 %4, 5
  %6 = add i32 %5, 6
  %7 = add i32 %6, 7
  %8 = add i32 %7, 8
  ret i32 %8
}

; Test cross-basic-block counting
define i32 @test_cross_bb_counting(i32 %a, i1 %cond) {
; CHECK-LABEL: test_cross_bb_counting:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, 1
; CHECK-NEXT:    addi a0, a0, 2
; CHECK-NEXT:    addi a0, a0, 3
; CHECK-NEXT:    addi a0, a0, 4
; CHECK-NEXT:    addi a0, a0, 5
; CHECK-NEXT:    addi a0, a0, 6
; CHECK-NEXT:    addi a0, a0, 7
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    addi x0, x0, 0
; CHECK-NEXT:    beqz a1, .LBB2_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    addi a0, a0, 10
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    addi a0, a0, 20
; CHECK-NEXT:    ret
  %1 = add i32 %a, 1
  %2 = add i32 %1, 2
  %3 = add i32 %2, 3
  %4 = add i32 %3, 4
  %5 = add i32 %4, 5
  %6 = add i32 %5, 6
  %7 = add i32 %6, 7
  %8 = add i32 %7, 8
  br i1 %cond, label %if.true, label %if.false

if.true:
  %9 = add i32 %8, 10
  ret i32 %9

if.false:
  %10 = add i32 %8, 20
  ret i32 %10
}

; Test small function (< 8 instructions) - should not insert NOP
define i32 @test_small_function(i32 %a) {
; CHECK-LABEL: test_small_function:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, 1
; CHECK-NEXT:    addi a0, a0, 2
; CHECK-NEXT:    ret
  %1 = add i32 %a, 1
  %2 = add i32 %1, 2
  ret i32 %2
}

; Test that NOP is not inserted after branch instruction
define i32 @test_no_nop_after_branch(i32 %a, i1 %cond) {
; CHECK-LABEL: test_no_nop_after_branch:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a0, a0, 1
; CHECK-NEXT:    addi a0, a0, 2
; CHECK-NEXT:    addi a0, a0, 3
; CHECK-NEXT:    addi a0, a0, 4
; CHECK-NEXT:    addi a0, a0, 5
; CHECK-NEXT:    addi a0, a0, 6
; CHECK-NEXT:    addi a0, a0, 7
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    addi x0, x0, 0
; CHECK-NEXT:    beqz a1, .LBB5_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    addi a0, a0, 10
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB5_2:
; CHECK-NEXT:    addi a0, a0, 20
; CHECK-NEXT:    ret
  %1 = add i32 %a, 1
  %2 = add i32 %1, 2
  %3 = add i32 %2, 3
  %4 = add i32 %3, 4
  %5 = add i32 %4, 5
  %6 = add i32 %5, 6
  %7 = add i32 %6, 7
  %8 = add i32 %7, 8
  br i1 %cond, label %if.true, label %if.false

if.true:
  %9 = add i32 %8, 10
  ret i32 %9

if.false:
  %10 = add i32 %8, 20
  ret i32 %10
}

